/* Optional browser smoke test: npm install playwright, then node scripts/test_frontend.cjs.
   Uses installed Edge on Windows, otherwise Playwright Chromium. */
const { chromium } = require('playwright');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  const root = path.resolve(__dirname, '..');
  const browser = await chromium.launch({headless: true, ...(process.platform === 'win32' ? {channel: 'msedge'} : {})});
  try {
    const page = await browser.newPage({viewport: {width: 1100, height: 900}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(process.env.TEST_FRONTEND_URL || 'http://127.0.0.1:8010/');
    await page.waitForFunction(() => document.querySelector('#connection').textContent === 'Workspace ready', null, {timeout: 90000});
    await page.locator('#files').setInputFiles([path.join(root, 'samples/sales.csv'), path.join(root, 'samples/sales-duplicate.csv')]);
    await page.locator('#upload').click();
    await page.waitForFunction(() => !document.querySelector('#analyze').disabled, null, {timeout: 120000});
    assert.match(await page.locator('#profile').textContent(), /amount/);
    await page.locator('#question').fill('sum amount and sum units and sum profit');
    await page.locator('#analyze').click();
    await page.locator('#clarification-form').waitFor({state: 'visible', timeout: 120000});
    await page.locator('input[name="choice"]').first().check();
    await page.locator('#answer').click();
    await page.locator('#output').waitFor({state: 'visible', timeout: 180000});
    assert.match(await page.locator('#narrative').textContent(), /Added/);
    assert.doesNotMatch(await page.locator('#narrative').textContent(), /source hashes|SQL/);
    assert.doesNotMatch(await page.locator('#profile').textContent(), /Warning:/);
    assert.equal(await page.locator('#notes').textContent(), '');
    await page.locator('#calculation-evidence').waitFor({state: 'visible', timeout: 30000});
    assert.match(await page.locator('#verification').textContent(), /Verification: passed/);
    assert.deepEqual(await page.locator('#metrics strong').allTextContents(), ['5000', '50', '1000']);
    const first = await page.evaluate(() => resultData);
    const download = page.waitForEvent('download');
    await page.locator('#download').click();
    assert.match((await download).suggestedFilename(), /^analysis-.*\.json$/);
    await page.locator('#rerun').click();
    await page.locator('#output').waitFor({state: 'hidden', timeout: 30000});
    await page.locator('#output').waitFor({state: 'visible', timeout: 180000});
    await page.locator('#calculation-evidence').waitFor({state: 'visible', timeout: 30000});
    assert.match(await page.locator('#verification').textContent(), /Verification: passed/);
    const second = await page.evaluate(() => resultData);
    assert.notEqual(second.analysis_id, first.analysis_id);
    assert.equal(second.verification.output_hash, first.verification.output_hash);
    await page.waitForFunction(() => !document.querySelector('#analyze').disabled);
    await page.locator('#question').fill('difference between amount and profit');
    await page.locator('#analyze').click();
    await page.locator('#clarification-form').waitFor({state: 'visible', timeout: 120000});
    await page.locator('input[name="choice"]').first().check();
    await page.locator('#answer').click();
    await page.locator('#output').waitFor({state: 'visible', timeout: 180000});
    await page.locator('#calculation-evidence').waitFor({state: 'visible', timeout: 30000});
    assert.deepEqual(await page.locator('#metrics strong').allTextContents(), ['5000', '1000', '4000']);
    assert.match(await page.locator('#narrative').textContent(), /5000 − 1000 = 4000/);
    await page.waitForFunction(() => !document.querySelector('#analyze').disabled);
    await page.locator('#question').fill('How much did we make in West?');
    await page.locator('#analyze').click();
    await page.locator('#clarification-form').waitFor({state: 'visible', timeout: 120000});
    await page.locator('input[name="choice"]').first().check();
    await page.locator('#answer').click();
    await page.locator('#output').waitFor({state: 'visible', timeout: 180000});
    await page.locator('#calculation-evidence').waitFor({state: 'visible', timeout: 30000});
    assert.deepEqual(await page.locator('#metrics strong').allTextContents(), ['3600']);
    assert.match(await page.locator('#narrative').textContent(), /region equals West/);
    await page.waitForFunction(() => !document.querySelector('#analyze').disabled);
    await page.locator('#question').fill('sum amount');
    await page.locator('#analyze').click();
    await page.locator('#cancel').waitFor({state:'visible',timeout:30000});
    await page.locator('#cancel').click();
    await page.locator('#output').waitFor({state:'visible',timeout:120000});
    assert.match(await page.locator('#verification').textContent(), /Outcome: cancelled/);
    assert.deepEqual(errors, []);
    const output = path.join(root, '.test-env'); fs.mkdirSync(output, {recursive: true});
    await page.screenshot({path: path.join(output, 'frontend.png'), fullPage: true});
    console.log('PASS: real browser upload, clarification, verified totals, evidence, download and rerun.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
